apiVersion: v1
kind: Service
metadata:
  name: service-node
  namespace: so1p2
spec:
  ports:
  - name: node-port
    port: 5003
    targetPort: 5003
  selector:
      app: deploy-node
  type: LoadBalancer