// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/pcalificacion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalificacionClient is the client API for Calificacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalificacionClient interface {
	InsertarCalificacion(ctx context.Context, in *CalificacionRequest, opts ...grpc.CallOption) (*CalificacionReply, error)
}

type calificacionClient struct {
	cc grpc.ClientConnInterface
}

func NewCalificacionClient(cc grpc.ClientConnInterface) CalificacionClient {
	return &calificacionClient{cc}
}

func (c *calificacionClient) InsertarCalificacion(ctx context.Context, in *CalificacionRequest, opts ...grpc.CallOption) (*CalificacionReply, error) {
	out := new(CalificacionReply)
	err := c.cc.Invoke(ctx, "/proto.Calificacion/InsertarCalificacion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalificacionServer is the server API for Calificacion service.
// All implementations must embed UnimplementedCalificacionServer
// for forward compatibility
type CalificacionServer interface {
	InsertarCalificacion(context.Context, *CalificacionRequest) (*CalificacionReply, error)
	mustEmbedUnimplementedCalificacionServer()
}

// UnimplementedCalificacionServer must be embedded to have forward compatible implementations.
type UnimplementedCalificacionServer struct {
}

func (UnimplementedCalificacionServer) InsertarCalificacion(context.Context, *CalificacionRequest) (*CalificacionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertarCalificacion not implemented")
}
func (UnimplementedCalificacionServer) mustEmbedUnimplementedCalificacionServer() {}

// UnsafeCalificacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalificacionServer will
// result in compilation errors.
type UnsafeCalificacionServer interface {
	mustEmbedUnimplementedCalificacionServer()
}

func RegisterCalificacionServer(s grpc.ServiceRegistrar, srv CalificacionServer) {
	s.RegisterService(&Calificacion_ServiceDesc, srv)
}

func _Calificacion_InsertarCalificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalificacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalificacionServer).InsertarCalificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calificacion/InsertarCalificacion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalificacionServer).InsertarCalificacion(ctx, req.(*CalificacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Calificacion_ServiceDesc is the grpc.ServiceDesc for Calificacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calificacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Calificacion",
	HandlerType: (*CalificacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertarCalificacion",
			Handler:    _Calificacion_InsertarCalificacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pcalificacion.proto",
}
