version: '3'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "database_container"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_monitoreo
    volumes:
      - ./backend_node/db_init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - back

  backend:
    build:
      context: ./backend_node
      dockerfile: Dockerfile
    image: 'gudiel/so1-back-node:1.0.0'
    env_file:
      - ./backend_node/.env
    ports:
      - "5001:5001"
    depends_on:
      - database
    restart: always
    networks:
      - back
      - front

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "gudiel/so1-front-react:1.0.1"
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - front

volumes:
  mysql-data:

networks:
  back:
  front: