version: '3'

services:
  database:
    image: 'mysql'
    container_name: "database_container"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - back

  backend:
    image: 'so1tarea3back'
    container_name: "backend_container"
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: database
      DB_PORT: 33061
      DB_NAME: db_biblioteca_musical
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - back
      - front

  frontend:
    image: 'so1tarea3front'
    container_name: "frontend_container"
    ports:
      - "5001:5001"
    depends_on:
      - backend
    networks:
      - front

volumes:
  mysql-data:

networks:
  back:
  front: