apiVersion: v1
kind: Secret
metadata:
  name: secret-env
  namespace: so1p2
type: Opaque
data:
  #HOST_SERVER_PYTHON : ''
  #PORT_SERVER_PYTHON : ''
  HOST_REDIS : ''
  PORT_REDIS : ''
  HOST_MYSQL : ''
  NAMEDB_MYSQL : ''
  USER_MYSQL : ''
  PASS_MYSQL : ''
  PORT_MYSQL : ''
  #HOST_GRPC_SERVER : ''